[project]
name = "mind-lantern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "yt-dlp>=2025.6.9",
]
